apiVersion: v1
kind: Service
metadata:
  name: "elastic"
  labels:
    app: elastic
    group: db
    role: master
    tier: backend
    env: dev
spec:
  ports:
    - name: restful
      port: 9200
      targetPort: 9200
    - name: internal
      port: 9300
      targetPort: 9300
  selector:
    app: elastic
    group: db
    role: master
    tier: backend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "elastic"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic
        group: db
        role: master
        tier: backend
        env: dev
    spec:
      containers:
      - name: elastic
        image: "library/elasticsearch:2.3.2"
        ports:
          - name: restful
            containerPort: 9200
          - name: internal
            containerPort: 9300
        volumeMounts:
          - name: elastic-local-storage
            mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-local-storage
        emptyDir: {}

