apiVersion: v1
kind: Service
metadata:
  name: "mongo"
  labels:
    app: mongo
    group: db
    role: master
    tier: backend
    env: dev
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
    group: db
    role: master
    tier: backend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "mongo"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        group: db
        role: master
        tier: backend
        env: dev
      annotations:
        version: "3.2"
    spec:
      containers:
      - name: mongo
        image: "tutum/mongodb:3.2"
        env:
          - name: MONGODB_USER
            value: mongo
          - name: MONGODB_PASS
            value: password
          - name: MONGODB_DATABASE
            value: mydb
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-local-storage
            mountPath: /data/db
      volumes:
      - name: mongo-local-storage
        emptyDir: {}

