apiVersion: v1
kind: Service
metadata:
  name: "todos-webapp"
  labels:
    app: todos-webapp
    group: webapp
    tier: frontend
    env: dev
    router.deis.io/routable: "true"
  annotations:
    router.deis.io/domains: todos
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: todos-webapp
    group: webapp
    tier: frontend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "todos-webapp"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: todos-webapp
        group: webapp
        tier: frontend
        env: dev
    spec:
      containers:
      - name: todos-webapp
        image: "krobots-lite/todos-webapp:0.1"
        ports:
        - containerPort: 3000



