apiVersion: v1
kind: Service
metadata:
  name: "redis-master"
  labels:
    app: redis
    group: kv
    role: master
    tier: backend
    env: dev
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    group: kv
    role: master
    tier: backend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "redis-master"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        group: kv
        role: master
        tier: backend
        env: dev
      annotations:
        version: "3.2.0"
    spec:
      containers:
      - name: master
        image: "library/redis:3.2.0-alpine"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-local-storage
            mountPath: /data
      volumes:
      - name: redis-local-storage
        emptyDir: {}


