apiVersion: v1
kind: Service
metadata:
  name: "kafka"
  labels:
    app: kafka
    group: msg
    role: master
    tier: backend
    env: dev
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
    group: msg
    role: master
    tier: backend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "kafka"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        group: msg
        role: master
        tier: backend
        env: dev
      annotations:
        version: "0.8.2.1"
    spec:
      containers:
      - name: kafka
        image: "spotify/kafka:latest"
        env:
          - name: ADVERTISED_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ADVERTISED_PORT
            value: "9092"
        ports:
          - containerPort: 9092
        resources:
          limits:
            cpu: 300m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi

