apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq"
  labels:
    app: rabbitmq
    group: msg
    role: master
    tier: backend
    env: dev
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
    group: msg
    role: master
    tier: backend
    env: dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "rabbitmq"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        group: msg
        role: master
        tier: backend
        env: dev
      annotations:
        version: "3.6.1"
    spec:
      containers:
      - name: rabbitmq
        image: "library/rabbitmq:3.6.1"
        env:
          - name: rabbitmq_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
          - containerPort: 5672

